apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime-translate-system
  namespace: careerhack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realtime-translate-system
  template:
    metadata:
      labels:
        app: realtime-translate-system
    spec:
      containers:
      - name: realtime-translate-system
        image: jimmyhealer/realtime-translate-system:latest
        ports:
          - containerPort: 5000
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/app/grp-secret.json"
          - name: GOOGLE_CLOUD_PROJECT
            value: "tsmccareerhack2025-icsd-grp1"
          - name: FLASK_ENV
            value: "development"
        volumeMounts:
          - name: grp-secret
            mountPath: /app/grp-secret.json
            subPath: grp-secret.json
      volumes:
        - name: grp-secret
          secret:
            secretName: grp-secret
        - name: sqlproxy-creds
          secret:
            secretName: cloud-sql-proxy-creds
---
apiVersion: v1
kind: Service
metadata:
  name: realtime-translate-system-service
  namespace: careerhack
spec:
  selector:
    app: realtime-translate-system
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realtime-translate-system-ingress
  namespace: careerhack
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - careerhack.programing.tw
    secretName: careerhack-tls
  rules:
  - host: careerhack.programing.tw
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: realtime-translate-system-service
            port:
              number: 5000
